---

- name: Cisco APIC controller configuration and queries
  hosts: apic
  connection: local
  gather_facts: no
  
  tasks:
  - include_vars: ../defaults/main.yml
  
  - include_tasks: ../tasks/epg.yml
